### PR TITLE
fix: Use brighter colors for better accessibility

### LINKED ISSUE #3: Preview text too dark
The text is quite a bit too dark to be readable in "preview" mode, i.e. when tabbing through keys:

image

I don't have any visual impairment so if I struggle it's likely impossible to read for people who don't have perfect vision.

In particular the dim blue can't be read against the black background.

It seems that your terminal shows the blue a bit differently:
image

### PR DESCRIPTION
**Pull request by corneliusroemer**
Resolves #3

Replace all `Colors:DarkCOLOR` with `Colors:COLOR`

The reason for the very dark colors before was the double darkening due to: a) background and b) dark version.

With this PR things are actually readable:
image

This is current `main`:
image

### CODE REVIEW

**Comment by rrfeng** [comment]
I installed jnv using brew just now, but the color seems not changed?
image

File: src/jnv.rs [hunk 1]
```diff
@@ -74,16 +74,16 @@ impl Jnv {
                 history: Default::default(),
                 prefix: String::from("❯❯ "),
                 mask: Default::default(),
-                prefix_style: StyleBuilder::new().fgc(Color::DarkCyan).build(),
-                active_char_style: StyleBuilder::new().bgc(Color::DarkMagenta).build(),
+                prefix_style: StyleBuilder::new().fgc(Color::Cyan).build(),
```
Comment (ynqa) [inline src/jnv.rs:77]: @corneliusroemer I would like to proceed with the merge, but please make a revision just regarding this https://github.com/ynqa/jnv/issues/3#issuecomment-2008950603.

**Review by ynqa — CHANGES_REQUESTED** [review]

**Comment by ynqa** [comment]
@rrfeng This pull request is not yet merged. So the color theme is still v0.1.0 instead.

**Comment by rrfeng** [comment]
> @rrfeng This pull request is not yet merged. So the color theme is still v0.1.0 instead.

Oh I missed the status of this pull request :D

File: src/jnv.rs (hunk 1 above)
Comment (corneliusroemer) [reply src/jnv.rs:77]: Thanks for your feedback! I'm not quite sure what exactly I should change here, can you make that change? You should have push rights to the branch!

Comment (corneliusroemer) [reply src/jnv.rs]: I've just made a change, turning one of the Cyans into Blue so that each color is used only once again

**Comment by corneliusroemer** [comment]
I've updated the PR as requested @ynqa

**Review by ynqa — APPROVED** [review]
LGTM! @corneliusroemer Thanks 👍

**Comment by corneliusroemer** [comment]
Excellent! Now just a new release 😎
